---
- hosts: 127.0.0.1
  connection: local
  vars:
    author: JP Mens
  tasks:
  - name: Create JANED
    action: user name=janed comment="Jane Doe" shell=/bin/bash createhome=yes home=/home/janed
  - include: mutt.yaml muttuser=janed
  - name: Create config file
    action: template src=templates/whazzup.in dest=/tmp/whazzup

